export const ACUPUNCTURE_POINTS: Record<string, string> = {
  'LI4': 'Hegu (LI4): Titik Komando Wajah dan Mulut. Mengeluarkan Angin (Eksterior), merangsang fungsi turun Paru-paru, mengatur keringat, menggerakkan Qi dan Darah, serta meredakan nyeri. (Hal. 712)',
  'ST36': 'Zusanli (ST36): Menguatkan Qi Lambung dan Limpa, menyehatkan Darah dan Yin, mengusir Dingin, menguatkan Zheng Qi. (Hal. 734)',
  'LV3': 'Taichong (LV3): Menenangkan Liver, menggerakkan Qi Liver yang stagnan, menenangkan Pikiran, menyehatkan Darah Liver. (Hal. 756)',
  'SP6': 'Sanyinjiao (SP6): Menyehatkan Yin, memperkuat Limpa, mengharmoniskan Liver dan Ginjal, menenangkan Pikiran. (Hal. 742)',
  'LU7': 'Lieque (LU7): Melepaskan Eksterior, mengeluarkan Angin, merangsang fungsi turun Paru-paru, mengatur Saluran Ren. (Hal. 708)',
  'KI3': 'Taixi (KI3): Menguatkan Ginjal (Yin dan Yang), memperkuat tulang punggung, mengatur rahim. (Hal. 762)',
  'HT7': 'Shenmen (HT7): Menenangkan Pikiran (Shen), menyehatkan Darah Jantung, membuka lubang Jantung. (Hal. 724)',
  'PC6': 'Neiguan (PC6): Membuka Dada, menggerakkan Qi Jantung, menenangkan Lambung, menenangkan Pikiran. (Hal. 772)',
  'GV20': 'Baihui (GV20): Menaikkan Yang Qi, menenangkan Liver, menenangkan Pikiran, menjernihkan indra. (Hal. 788)',
  'CV4': 'Guanyuan (CV4): Menguatkan Qi Ginjal, menyehatkan Darah dan Yin, menguatkan Yang, mengatur rahim. (Hal. 794)',
  'CV6': 'Qihai (CV6): Menguatkan Qi seluruh tubuh, menaikkan Qi, mengatur rahim. (Hal. 796)',
  'BL20': 'Pishu (BL20): Back-Shu Limpa. Menguatkan Qi dan Yang Limpa, mengubah Lembab. (Hal. 748)',
  'BL23': 'Shenshu (BL23): Back-Shu Ginjal. Menguatkan Qi, Yin, dan Yang Ginjal, memperkuat punggung. (Hal. 768)',
  'LV2': 'Xingjian (LV2): Membersihkan Api Liver, menenangkan Angin Liver, mendinginkan Darah. (Hal. 754)',
  'ST40': 'Fenglong (ST40): Mengubah Dahak (Phlegm) dan Lembab, menenangkan Pikiran. (Hal. 738)',
  'SP9': 'Yinlingquan (SP9): Mengeluarkan Lembab dari Jiao Bawah, membuka saluran air. (Hal. 744)',
  'GB20': 'Fengchi (GB20): Mengeluarkan Angin (Interior/Eksterior), menenangkan Liver, menjernihkan mata. (Hal. 782)',
  'GB34': 'Yanglingquan (GB34): Menguntungkan Tendon dan Sendi, menggerakkan Qi Liver, membersihkan Lembab-Panas Empedu. (Hal. 784)',
  'BL13': 'Feishu (BL13): Back-Shu Paru. Menguatkan Qi Paru, merangsang fungsi turun Paru, melepaskan Eksterior. (Hal. 706)',
  'BL15': 'Xinshu (BL15): Back-Shu Jantung. Menyehatkan Darah Jantung, menenangkan Pikiran, mengatur Jantung. (Hal. 722)',
  'BL18': 'Ganshu (BL18): Back-Shu Liver. Menyehatkan Darah Liver, menggerakkan Qi Liver, menjernihkan mata. (Hal. 752)',
  'BL21': 'Weishu (BL21): Back-Shu Lambung. Menguatkan Qi Lambung, merangsang fungsi turun Lambung. (Hal. 736)',
  'ST25': 'Tianshu (ST25): Mengatur Usus Besar, menghentikan diare, membersihkan Lembab-Panas. (Hal. 732)',
  'CV12': 'Zhongwan (CV12): Menguatkan Lambung dan Limpa, mengubah Dahak, merangsang fungsi turun Lambung. (Hal. 730)',
  'CV17': 'Shanzhong (CV17): Menguatkan Qi Dada (Zong Qi), menggerakkan Qi di dada, menguntungkan Paru-paru. (Hal. 710)',
  'LV14': 'Qimen (LV14): Front-Mu Liver. Menggerakkan Qi Liver, mengharmoniskan Liver dan Lambung. (Hal. 758)',
  'GB21': 'Jianjing (GB21): Menggerakkan Qi, menaikkan Yang, menguntungkan payudara, mempercepat persalinan. (Hal. 780)',
  'LI11': 'Quchi (LI11): Membersihkan Panas, mendinginkan Darah, mengeluarkan Angin, mengusir Lembab. (Hal. 714)',
  'TE5': 'Waiguan (TE5): Melepaskan Eksterior, mengeluarkan Angin-Panas, menguntungkan telinga. (Hal. 776)',
  'SI3': 'Houxi (SI3): Membuka Saluran Du, mengeluarkan Angin, menenangkan Pikiran, menguntungkan tulang punggung. (Hal. 718)',
  'LV8': 'Ququan (LV8): Titik He-Sea Liver. Menyehatkan Darah Liver, menutrisi Yin Liver, membersihkan Lembab-Panas dari Jiao Bawah. (Hal. 755)',
  'BL17': 'Geshu (BL17): Titik Influential Darah. Menyehatkan Darah, menggerakkan Darah, membersihkan Panas dari Darah. (Hal. 720)',
  'GB13': 'Benshen (GB13): Menenangkan Pikiran (Shen), menenangkan Liver, mengusir Angin. (Hal. 781)',
  'KI7': 'Fuliu (KI7): Menguatkan Yang Ginjal, mengatur saluran air dan keringat, mengusir Lembab. (Hal. 764)',
  'SP3': 'Taibai (SP3): Titik Yuan-Source Limpa. Menguatkan Limpa, mengubah Lembab, mengharmoniskan Lambung. (Hal. 741)',
  'LU9': 'Taiyuan (LU9): Titik Yuan-Source Paru. Menguatkan Qi Paru, mengubah Dahak, mengatur pembuluh darah. (Hal. 709)',
  'HT3': 'Shaohai (HT3): Titik He-Sea Jantung. Menenangkan Pikiran, membersihkan Panas Jantung, mengubah Dahak. (Hal. 721)',
  'BL25': 'Dachangshu (BL25): Back-Shu Usus Besar. Mengatur Usus Besar, menghentikan diare, menguatkan punggung. (Hal. 770)',
  'BL28': 'Pangguangshu (BL28): Back-Shu Kandung Kemih. Mengatur Kandung Kemih, mengeluarkan Lembab-Panas. (Hal. 771)',
  'CV22': 'Tiantu (CV22): Merangsang fungsi turun Paru, menghentikan batuk, mengubah Dahak, menguntungkan tenggorokan. (Hal. 798)',
  'GV14': 'Dazhui (GV14): Titik pertemuan semua saluran Yang. Membersihkan Panas, melepaskan Eksterior, menenangkan Liver. (Hal. 786)',
  'LI20': 'Yingxiang (LI20): Membuka hidung, mengeluarkan Angin, membersihkan Panas. (Hal. 713)',
  'ST44': 'Neiting (ST44): Titik Ying-Spring Lambung. Membersihkan Panas Lambung, mengatur Usus, meredakan nyeri. (Hal. 739)',
  'SI19': 'Tinggong (SI19): Menguntungkan telinga, menenangkan Pikiran, membersihkan Panas. (Hal. 719)',
  'GB41': 'Zulinqi (GB41): Membuka Saluran Dai, menggerakkan Qi Liver, menguntungkan payudara, menjernihkan mata. (Hal. 785)',
  'LR1': 'Dadun (LR1): Titik Jing-Well Liver. Mengatur menstruasi, mengembalikan kesadaran, mengatur Jiao Bawah. (Hal. 753)',
  'LR5': 'Ligou (LR5): Titik Luo-Connecting Liver. Menggerakkan Qi Liver, membersihkan Lembab-Panas dari Jiao Bawah. (Hal. 754)',
  'SP10': 'Xuehai (SP10): Lautan Darah. Menyehatkan Darah, menggerakkan Darah, mendinginkan Darah, mengatur menstruasi. (Hal. 745)',
  'BL40': 'Weizhong (BL40): Titik Komando untuk punggung bawah. Membersihkan Panas, menguntungkan kandung kemih, mendinginkan Darah. (Hal. 769)',
  'BL60': 'Kunlun (BL60): Mengeluarkan Angin, membersihkan Panas, menguatkan punggung, mempercepat persalinan. (Hal. 772)',
  'KI6': 'Zhaohai (KI6): Membuka Saluran Yin Qiao, menguntungkan tenggorokan, menenangkan Pikiran, menyehatkan Yin Ginjal. (Hal. 763)',
  'LU5': 'Chize (LU5): Titik He-Sea Paru. Membersihkan Panas Paru, merangsang fungsi turun Paru, mengusir Dahak. (Hal. 707)',
  'LI10': 'Shousanli (LI10): Mengatur Qi dan Darah, mengharmoniskan Usus dan Lambung. (Hal. 713)',
  'ST21': 'Liangmen (ST21): Mengatur Lambung, menurunkan Qi yang memberontak, menghentikan nyeri. (Hal. 731)',
  'GB30': 'Huantiao (GB30): Menguntungkan pinggul dan kaki, mengusir Angin-Lembab, menggerakkan Qi dan Darah. (Hal. 783)',
  'GB39': 'Xuanzhong (GB39): Titik Influential Sumsum (Marrow). Menguntungkan tulang dan sumsum, mengusir Angin-Lembab. (Hal. 786)',
};
